FROM python:3.10-slim

WORKDIR /app

COPY . /app
COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r /app/requirements.txt

CMD ["bash"]